# Generated by Django 4.0.1 on 2022-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='coordinates',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
