# Generated by Django 4.0.1 on 2022-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_point_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='coordinates',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='point',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
