# Generated by Django 4.0.1 on 2022-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_coordinates_point_lat_point_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='point',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
