# Generated by Django 4.0.1 on 2022-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_point_description_point_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='category',
            field=models.CharField(choices=[('Grocery Store', 'Grocery Store'), ('Liquor Store', 'Liquor Store'), ('Retail Store', 'Retail Store')], default='Grocery Store', max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='point',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
