# Generated by Django 4.0.1 on 2022-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_point_category_alter_point_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='category',
            field=models.CharField(choices=[('Dagligvarehandel', 'Dagligvarehandel'), ('Vinmonopol', 'Vinmonopol')], default='Dagligvarehandel', max_length=100),
        ),
    ]
