# Generated by Django 4.0.1 on 2022-04-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_point_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='created',
        ),
    ]
